### ISSUE TITLE
Support XSD-to-CMF transform

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-API#11]
Support the XSD-to-CMF (x2m) transform from the CMF tool.

Input:

- XSD file *OR* 
- zip file with a set of XSDs

Output: 

- .cmf file
- .cmx file

**Comment by petermadruga** [comment]
I'm getting closer. Today I was able to make the call from the API and get the CMFTool to generate the .CMF and .CMX files locally. Now I need to move the test into the docker containers to see if there are any issues there.

**Comment by petermadruga** [comment]
This feature is working, though instead of returning two files, it returns a zip file with the .cmf and .cmx files in it.
