### ISSUE TITLE
Set up user authentication

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-API#8]
NIEM API 2.0 will support community content and thus will need to support user permissions for specific models.  Set up user authentication for the database and for

- [x] Create and manage accounts (e.g., reset password)
- [x] Add authentication support
- [x] Set up a simple authenticated API call for testing

Notes: 

- ConTesA has user accounts
- Work with BAH re permission and the user experience between MEP Builder and the NIEM API.  Users shouldn't need to log in with two sets of credentials.

**Comment by petermadruga** [comment]
Sent an email to Nick Saney to discuss best practices for user security in the API. Bearer tokens such as JWToken may be the right approach but I'll add more details once I talk with Nick.

**Comment by petermadruga** [comment]
Met with Nick Saney and I have started writing a document to detail the implementation of security for the NIEM API.

**Comment by petermadruga** [comment]
At this time, I have basic authentication working. Once Christina merges her database, we can add entities for UserModelPermissions and UserNamespacePermissions.
